### ISSUE TITLE
Issue with composer require systopia/expression-language-ext not Installing Correctly

### ISSUE THREAD

**Issue by connecttoveera** [systopia/expression-language-ext#4]
I am trying to install the systopia/expression-language-ext package using Composer in my Drupal 10 project, but I'm facing an issue where the package is not installing correctly, and I'm unable to use the classes provided by the package.

composer require systopia/expression-language-ext
./composer.json has been updated
Running composer update systopia/expression-language-ext
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires systopia/expression-language-ext * -> satisfiable by systopia/expression-language-ext[dev-main, v0.1.0, 9999999-dev].
    - systopia/expression-language-ext[dev-main, v0.1.0] require symfony/expression-language ^5 || ^6 -> found symfony/expression-language[v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev] but it conflicts with your root composer.json require (^7.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require systopia/expression-language-ext:*" to figure out if any version is installable, or "composer require systopia/expression-language-ext:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by dontub** [comment]
Fixed in v0.1.1. Thanks for reporting.
